package Controller;

import Model.dao.AdminDAO;
import Model.dto.AdminDto;
import Model.entity.AdminEntity;
import View.AdminAddAdminPanel;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.text.ParseException;

public class AdminController {

    private AdminAddAdminPanel view;
    private AdminDAO dao;

    public AdminController(AdminAddAdminPanel view) {
        this.view = view;
        try {
            this.dao = new AdminDAO();
            loadTableData();
        } catch (Exception e) { System.out.println("Admin Controller Load Error: " + e.getMessage()); }
    }

    private boolean isValidDate(String date) {
        if (!date.matches("^\\d{4}-\\d{2}-\\d{2}$")) return false;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false);
        try { sdf.parse(date); return true; } catch (ParseException e) { return false; }
    }

    public void addAdmin() {
        AdminDto dto = view.getAdminData();

        if (dto.getName().trim().isEmpty() || dto.getNic().trim().isEmpty() ||
            dto.getBirthday().trim().isEmpty() || dto.getContactNumber().trim().isEmpty() || 
            dto.getEmail().trim().isEmpty() || dto.getAddress().trim().isEmpty() || 
            dto.getSalary().trim().isEmpty() || dto.getPassword().trim().isEmpty()) {
            JOptionPane.showMessageDialog(view, "Please fill in all the required fields!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!isValidDate(dto.getBirthday())) {
            JOptionPane.showMessageDialog(view, "Invalid Birthday! Use YYYY-MM-DD", "Error", JOptionPane.ERROR_MESSAGE); return;
        }
        if (!dto.getContactNumber().matches("^\\d{10}$")) {
            JOptionPane.showMessageDialog(view, "Invalid Contact Number!", "Error", JOptionPane.ERROR_MESSAGE); return;
        }

        double salaryVal = 0.0;
        try { salaryVal = Double.parseDouble(dto.getSalary()); } 
        catch (NumberFormatException e) { JOptionPane.showMessageDialog(view, "Invalid Salary Amount!", "Error", JOptionPane.ERROR_MESSAGE); return; }

        AdminEntity entity = new AdminEntity(
            dto.getAdminId(), dto.getName(), dto.getNic(), dto.getBirthday(), dto.getContactNumber(),
            dto.getEmail(), dto.getAddress(), dto.getGender(), salaryVal, dto.getPassword(), dto.getStatus()
        );

        if (dao.addAdmin(entity)) {
            JOptionPane.showMessageDialog(view, "Admin Added Successfully!");
            
            // --- Email Service එක මෙතනින් කනෙක්ට් කර ඇත (Welcome Email) ---
            new Thread(() -> AddAdminEmailService.sendWelcomeEmail(dto)).start();
            
            view.clearFields();
            view.loadAutoGeneratedId();
            loadTableData();
        } else {
            JOptionPane.showMessageDialog(view, "Failed to Add Admin! Email or NIC might already exist.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void loadTableData() {
        List<AdminEntity> admins = dao.getAllAdmins();
        DefaultTableModel model = (DefaultTableModel) view.getTable().getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{"Admin ID", "Name", "NIC", "Contact", "Email", "Salary", "Status"});
        
        for (AdminEntity a : admins) {
            model.addRow(new Object[]{ a.getAdminId(), a.getName(), a.getNic(), a.getContactNumber(), a.getEmail(), a.getSalary(), a.getStatus() });
        }
    }

    public void searchAdmin() {
        String searchId = view.getSearchId();
        if (searchId == null || searchId.trim().isEmpty()) { JOptionPane.showMessageDialog(view, "Please enter an Admin ID!"); return; }

        AdminEntity admin = dao.searchAdmin(searchId.trim());
        if (admin != null) {
            AdminDto dto = new AdminDto(
                admin.getAdminId(), admin.getName(), admin.getNic(), admin.getBirthday(),
                admin.getContactNumber(), admin.getEmail(), admin.getAddress(), admin.getGender(),
                String.valueOf(admin.getSalary()), admin.getPassword(), admin.getStatus()
            );
            view.setAdminData(dto);
            JOptionPane.showMessageDialog(view, "Admin Record Found!");
        } else {
            JOptionPane.showMessageDialog(view, "Admin Not Found!", "Error", JOptionPane.ERROR_MESSAGE);
            view.clearFields(); view.loadAutoGeneratedId();
        }
    }

    public void updateAdmin() {
        AdminDto dto = view.getAdminData();
        double salaryVal = 0.0;
        try { salaryVal = Double.parseDouble(dto.getSalary()); } 
        catch (NumberFormatException e) { JOptionPane.showMessageDialog(view, "Invalid Salary Amount!"); return; }

        AdminEntity entity = new AdminEntity(
            dto.getAdminId(), dto.getName(), dto.getNic(), dto.getBirthday(), dto.getContactNumber(),
            dto.getEmail(), dto.getAddress(), dto.getGender(), salaryVal, dto.getPassword(), dto.getStatus()
        );

        if (dao.updateAdmin(entity)) {
            JOptionPane.showMessageDialog(view, "Admin Updated Successfully!");
            
            // --- Email Service එක මෙතනින් කනෙක්ට් කර ඇත (Update Email) ---
            new Thread(() -> AddAdminEmailService.sendUpdateEmail(dto)).start();
            
            view.clearFields(); view.loadAutoGeneratedId(); loadTableData();
        } else { JOptionPane.showMessageDialog(view, "Update Failed!", "Error", JOptionPane.ERROR_MESSAGE); }
    }

    public void deleteAdmin() {
        String adminId = view.getAdminData().getAdminId();
        AdminEntity admin = dao.searchAdmin(adminId);
        if (admin == null) { JOptionPane.showMessageDialog(view, "Admin Not Found!"); return; }

        int confirm = JOptionPane.showConfirmDialog(view, "Are you sure you want to delete this admin?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (dao.deleteAdmin(adminId)) {
                JOptionPane.showMessageDialog(view, "Admin Deleted Successfully!");
                
                // --- Email Service එක මෙතනින් කනෙක්ට් කර ඇත (Delete Email) ---
                new Thread(() -> AddAdminEmailService.sendDeleteEmail(admin.getEmail(), admin.getName(), adminId)).start();
                
                view.clearFields(); view.loadAutoGeneratedId(); loadTableData();
            } else { JOptionPane.showMessageDialog(view, "Delete Failed!", "Error", JOptionPane.ERROR_MESSAGE); }
        }
    }

    // Excel CSV Export
    public void exportToExcel() {
        String headers = "Admin ID,Full Name,NIC,Birthday,Contact Number,Email,Address,Gender,Salary,Status,Reg. Date";
        List<String> dataRows = new ArrayList<>();
        List<AdminEntity> admins = dao.getAllAdmins();

        for (AdminEntity a : admins) {
            String safeAddress = a.getAddress() != null ? a.getAddress().replace(",", " ") : "";
            String row = a.getAdminId() + "," + a.getName() + "," + a.getNic() + "," + a.getBirthday() + "," +
                         a.getContactNumber() + "," + a.getEmail() + "," + safeAddress + "," + a.getGender() + "," +
                         a.getSalary() + "," + a.getStatus() + "," + a.getRegistrationDate();
            dataRows.add(row);
        }
        ExcelExportConnection.ExcelExportService.exportToCSV(view, "Admins_Official_Report.csv", headers, dataRows);
    }

   // Export Data to PDF 
    public void exportToPDF() {
        StringBuilder htmlBuilder = new StringBuilder();
        htmlBuilder.append("<!DOCTYPE html>");
        htmlBuilder.append("<html><head><style>")
                   .append("body { font-family: Helvetica, Arial, sans-serif; color: #333333; } ")
                   .append("table { width: 100%; border-collapse: collapse; font-size: 11px; margin-top: 10px; } ")
                   // Premium Black පැහැති Header එක
                   .append("th { background-color: #1C1C1C; color: #ffffff; padding: 10px; border: 1px solid #0A0A0A; text-align: left; } ")
                   .append("td { padding: 8px; border: 1px solid #dddddd; } ")
                   // ලා අළු පැහැයක් Even පේළි සඳහා (Black Theme එකට ගැළපෙන්න)
                   .append(".even-row { background-color: #F8F8F8; } ")
                   .append(".odd-row { background-color: #ffffff; } ")
                   .append(".status-active { color: #008000; font-weight: bold; } ")
                   .append(".status-inactive { color: #d9534f; font-weight: bold; } ")
                   .append("</style></head><body>");
        
        htmlBuilder.append("<div style='text-align: center; margin-bottom: 25px;'>");
        htmlBuilder.append("<img src='https://anucentralcollege.com/og-image.jpg' width='85' height='85' />");
        // මාතෘකාවටත් Premium Black පැහැය
        htmlBuilder.append("<h1 style='color: #1C1C1C; margin: 10px 0 2px 0; font-size: 24px; letter-spacing: 1px;'>")
                   .append("CENTRAL COLLEGE ANURADHAPURA</h1>");
        htmlBuilder.append("<h3 style='color: #666666; margin: 0; font-size: 14px; text-transform: uppercase;'>")
                   .append("Official Executive Administrator Report</h3>");
        // රන්වන් (Gold) පැහැති ඉර
        htmlBuilder.append("<hr style='border: 0; border-bottom: 2px solid #D4AF37; margin-top: 15px;' />");
        htmlBuilder.append("</div>");
        
        htmlBuilder.append("<table>");
        htmlBuilder.append("<tr>")
                   .append("<th>Admin ID</th>")
                   .append("<th>Full Name</th>")
                   .append("<th>NIC</th>")
                   .append("<th>Birthday</th>")
                   .append("<th>Contact</th>")
                   .append("<th>Email</th>")
                   .append("<th>Address</th>")
                   .append("<th>Gender</th>")
                   .append("<th>Salary (Rs)</th>")
                   .append("<th>Status</th>")
                   .append("<th>Reg. Date</th>")
                   .append("</tr>");

        java.util.List<Model.entity.AdminEntity> admins = dao.getAllAdmins();
        boolean isEvenRow = false;
        
        for(Model.entity.AdminEntity a : admins) {
            String rowClass = isEvenRow ? "even-row" : "odd-row";
            htmlBuilder.append("<tr class='").append(rowClass).append("'>");
            
            // Admin ID එක කැපී පෙනෙන්න තද කළු පැහැයක්
            htmlBuilder.append("<td style='color: #1C1C1C; font-weight: bold;'>").append(a.getAdminId()).append("</td>");
            htmlBuilder.append("<td>").append(a.getName()).append("</td>");
            htmlBuilder.append("<td>").append(a.getNic()).append("</td>");
            htmlBuilder.append("<td>").append(a.getBirthday()).append("</td>");
            htmlBuilder.append("<td>").append(a.getContactNumber()).append("</td>");
            htmlBuilder.append("<td>").append(a.getEmail()).append("</td>");
            htmlBuilder.append("<td>").append(a.getAddress()).append("</td>");
            htmlBuilder.append("<td>").append(a.getGender()).append("</td>");
            htmlBuilder.append("<td>").append(a.getSalary()).append("</td>");
            
            String statusClass = a.getStatus().equalsIgnoreCase("Active") ? "status-active" : "status-inactive";
            htmlBuilder.append("<td class='").append(statusClass).append("'>").append(a.getStatus()).append("</td>");
            
            htmlBuilder.append("<td>").append(a.getRegistrationDate()).append("</td>");
            htmlBuilder.append("</tr>");
            
            isEvenRow = !isEvenRow; 
        }
        
        htmlBuilder.append("</table>");
        
        // Notification කොටසටත් Black border එකක්
        htmlBuilder.append("<div style='margin-top: 25px; padding: 12px 15px; background-color: #F8F8F8; border-left: 4px solid #1C1C1C;'>");
        htmlBuilder.append("<p style='font-size: 11px; color: #444444; margin: 0; line-height: 1.6;'>");
        htmlBuilder.append("<strong style='color: #1C1C1C;'>OFFICIAL SYSTEM NOTIFICATION:</strong><br/>");
        htmlBuilder.append("This is a computer-generated official report produced by the Central College Anuradhapura Administration Portal. ");
        htmlBuilder.append("As an electronically generated document, it does not require a physical signature or stamp for validation. ");
        htmlBuilder.append("Any discrepancies should be reported to the system administration immediately.");
        htmlBuilder.append("</p>");
        htmlBuilder.append("</div>");
        
        String currentdate = DateandTimeConnection.DateandTimeConnection.getInstance().getCurrentDate();
        
        htmlBuilder.append("<div style='margin-top: 30px; border-top: 1px solid #eeeeee; padding-top: 10px; text-align: center;'>");
        htmlBuilder.append("<p style='font-size: 10px; color: #888888; margin: 0;'>");
        htmlBuilder.append("Generated by Central College Anuradhapura Administration Portal | " + currentdate);
        htmlBuilder.append("</p>");
        htmlBuilder.append("</div>");
        
        htmlBuilder.append("</body></html>");
        
        try {
            PdfExportConnection.PdfExportConnection.getInstance().exportHTMLtoPDF(
                view, 
                "Admins_Official_Report.pdf", 
                htmlBuilder.toString()
            );
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(view, "Error Generating PDF: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
}