package Controller;

import Model.dao.AdminStudentDAO;
import Model.dto.StudentDto;
import Model.entity.StudentEntity;
import View.AdminAddStuPanel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AdminStudentController {
    
    private AdminAddStuPanel view;
    private AdminStudentDAO dao;

    public AdminStudentController(AdminAddStuPanel view) {
        this.view = view;
        try {
            this.dao = new AdminStudentDAO();
            loadTableData(); 
        } catch (Exception e) {
            System.out.println("Controller Load Error: " + e.getMessage());
        }
    }

    public void addStudent() {
        StudentDto dto = view.getStudentData();
        StudentEntity entity = new StudentEntity(
            dto.getStudentId(), dto.getName(), dto.getBirthday(), dto.getContactNumber(), 
            dto.getEmail(), dto.getAddress(), dto.getGender(), dto.getPassword(), dto.getStatus()
        );
        
        if (dao.addStudent(entity)) {
            JOptionPane.showMessageDialog(view, "Student Added Successfully!");
            
            // Email 
            // Secure Background Thread 
            new Thread(() -> {
                AddStuEmailService.sendWelcomeEmail(dto);
            }).start();
            
            // UI Update
            view.clearFields();
            //Auto GeneratedId
            view.loadAutoGeneratedId(); 
            loadTableData();
        } else {
            JOptionPane.showMessageDialog(view, "Failed to Add Student!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void loadTableData() {
        List<StudentEntity> students = dao.getAllStudents();
        DefaultTableModel model = (DefaultTableModel) view.getTable().getModel();
        model.setRowCount(0); 
        
        model.setColumnIdentifiers(new Object[]{"Student ID", "Name", "Contact", "Email", "Gender", "Status"});
        
        for (StudentEntity s : students) {
            model.addRow(new Object[]{
                s.getStudentId(), s.getName(), s.getContactNumber(), s.getEmail(), s.getGender(), s.getStatus()
            });
        }
    }
}