package Controller;

import Model.dao.AdminStudentDAO;
import Model.dto.StudentDto;
import Model.entity.StudentEntity;
import View.AdminAddStuPanel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.text.ParseException;

public class AdminStudentController {
    
    private AdminAddStuPanel view;
    private AdminStudentDAO dao;

    public AdminStudentController(AdminAddStuPanel view) {
        this.view = view;
        try {
            this.dao = new AdminStudentDAO();
            loadTableData(); 
        } catch (Exception e) {
            System.out.println("Controller Load Error: " + e.getMessage());
        }
    }

    public void addStudent() {
        StudentDto dto = view.getStudentData();
        
        // Empty Field Validation
        if (dto.getName().trim().isEmpty() || 
            dto.getBirthday().trim().isEmpty() || 
            dto.getContactNumber().trim().isEmpty() || 
            dto.getEmail().trim().isEmpty() || 
            dto.getAddress().trim().isEmpty() || 
            dto.getPassword().trim().isEmpty()) {
            
            JOptionPane.showMessageDialog(view, "Please fill in all the required fields!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return; 
        }

        // Name Validation
        if (!dto.getName().matches("^[a-zA-Z\\s]+$")) {
            JOptionPane.showMessageDialog(view, "Invalid Name! The name can only contain letters and spaces.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3.Birthday Validation) - YYYY-MM-DD
        if (!isValidDate(dto.getBirthday())) {
            JOptionPane.showMessageDialog(view, "Invalid Birthday! Please enter a valid date in YYYY-MM-DD format (e.g. 2005-01-25).", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Contact Number Validation
        if (!dto.getContactNumber().matches("^\\d{10}$")) {
            JOptionPane.showMessageDialog(view, "Invalid Contact Number! Please enter a valid 10-digit phone number.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Email Validation
        if (!dto.getEmail().matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
            JOptionPane.showMessageDialog(view, "Invalid Email Address! Please enter a valid email (e.g. example@gmail.com).", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //if Validations Sucessfull pass data to database
        StudentEntity entity = new StudentEntity(
            dto.getStudentId(), dto.getName(), dto.getBirthday(), dto.getContactNumber(), 
            dto.getEmail(), dto.getAddress(), dto.getGender(), dto.getPassword(), dto.getStatus()
        );
        
        if (dao.addStudent(entity)) {
            JOptionPane.showMessageDialog(view, "Student Added Successfully!");
            
            // Pass data to mail method
            new Thread(() -> {
                AddStuEmailService.sendWelcomeEmail(dto);
            }).start();
            
            view.clearFields();
            view.loadAutoGeneratedId(); 
            loadTableData();
        } else {
            JOptionPane.showMessageDialog(view, "Failed to Add Student! Email might already exist or Database error.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    //  Date Validation
    private boolean isValidDate(String date) {
        // date format validation YYYY-MM-DD 
        if (!date.matches("^\\d{4}-\\d{2}-\\d{2}$")) {
            return false;
        }
        // chick it real time date
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false);
        try {
            sdf.parse(date);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }

    public void loadTableData() {
        List<StudentEntity> students = dao.getAllStudents();
        DefaultTableModel model = (DefaultTableModel) view.getTable().getModel();
        model.setRowCount(0); 
        
        model.setColumnIdentifiers(new Object[]{"Student ID", "Name", "Contact", "Email", "Gender", "Status"});
        
        for (StudentEntity s : students) {
            model.addRow(new Object[]{
                s.getStudentId(), s.getName(), s.getContactNumber(), s.getEmail(), s.getGender(), s.getStatus()
            });
        }
    }
// Search Student
    public void searchStudent() {
        // getSearchId
        String searchId = view.getSearchId(); 
        
        if (searchId == null || searchId.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(view, "Please enter a Student ID to search!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //seartch student id from ID Database 
        StudentEntity student = dao.searchStudent(searchId.trim()); 
        
        if (student != null) {
            StudentDto dto = new StudentDto(
                student.getStudentId(), student.getName(), student.getBirthday(), student.getContactNumber(),
                student.getEmail(), student.getAddress(), student.getGender(), student.getPassword(), student.getStatus()
            );
            
            // Send data to View Fields 
            view.setStudentData(dto); 
            javax.swing.JOptionPane.showMessageDialog(view, "Student Record Found!");
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(view, "Student Not Found!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            view.clearFields();
            view.loadAutoGeneratedId(); // generate auto id
        }
    }

    // 2. Update Student
    public void updateStudent() {
        StudentDto dto = view.getStudentData();
        // (මෙහිදීද Add එකේ මෙන් හිස්තැන් සහ Regex Validation එකතු කරගන්න)
        
        StudentEntity entity = new StudentEntity(
            dto.getStudentId(), dto.getName(), dto.getBirthday(), dto.getContactNumber(), 
            dto.getEmail(), dto.getAddress(), dto.getGender(), dto.getPassword(), dto.getStatus()
        );
        
        if (dao.updateStudent(entity)) {
            JOptionPane.showMessageDialog(view, "Student Updated Successfully!");
            new Thread(() -> AddStuEmailService.sendUpdateEmail(dto)).start();
            view.clearFields();
            view.loadAutoGeneratedId();
            loadTableData();
        } else {
            JOptionPane.showMessageDialog(view, "Update Failed!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // 3. Delete Student
    public void deleteStudent() {
        // get ID using form student id label
         String studentId = view.getStudentData().getStudentId();
        
        //get all student details use foe email
        StudentEntity student = dao.searchStudent(studentId);
        
        if (student == null) {
            JOptionPane.showMessageDialog(view, "Student Not Found to Delete!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(view, "Are you sure you want to delete this student?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (dao.deleteStudent(studentId)) {
                JOptionPane.showMessageDialog(view, "Student Deleted Successfully!");
                
                // Send Email
                String email = student.getEmail();
                String name = student.getName();
                new Thread(() -> AddStuEmailService.sendDeleteEmail(email, name, studentId)).start();
                
                view.clearFields();
                view.loadAutoGeneratedId();
                loadTableData();
            } else {
                JOptionPane.showMessageDialog(view, "Delete Failed!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
}