package Controller;

import Model.dao.AdminTeacherDAO;
import Model.dto.TeacherDto;
import Model.entity.TeacherEntity;
import View.AdminAddTeacherPanel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.text.ParseException;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
public class AdminTeacherController {
    
    private AdminAddTeacherPanel view;
    private AdminTeacherDAO dao;

    public AdminTeacherController(AdminAddTeacherPanel view) {
        this.view = view;
        try {
            this.dao = new AdminTeacherDAO();
            loadTableData(); 
        } catch (Exception e) {
            System.out.println("Controller Load Error: " + e.getMessage());
        }
    }

  

    // Validation Method for Date
    private boolean isValidDate(String date) {
        if (!date.matches("^\\d{4}-\\d{2}-\\d{2}$")) return false;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false);
        try { sdf.parse(date); return true; } 
        catch (ParseException e) { return false; }
    }

    public void addTeacher() {
        TeacherDto dto = view.getTeacherData();
        
        // Empty Check
        if (dto.getName().trim().isEmpty() || dto.getNic().trim().isEmpty() || 
            dto.getBirthday().trim().isEmpty() || dto.getContactNumber().trim().isEmpty() || 
            dto.getEmail().trim().isEmpty() || dto.getAddress().trim().isEmpty() || 
            dto.getSalary().trim().isEmpty() || dto.getPassword().trim().isEmpty()) {
            JOptionPane.showMessageDialog(view, "Please fill in all the required fields!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return; 
        }

        // Field Validations
        if (!dto.getName().matches("^[a-zA-Z\\s]+$")) {
            JOptionPane.showMessageDialog(view, "Invalid Name!", "Error", JOptionPane.ERROR_MESSAGE); return;
        }
        if (!isValidDate(dto.getBirthday())) {
            JOptionPane.showMessageDialog(view, "Invalid Birthday! Use YYYY-MM-DD", "Error", JOptionPane.ERROR_MESSAGE); return;
        }
        if (!dto.getContactNumber().matches("^\\d{10}$")) {
            JOptionPane.showMessageDialog(view, "Invalid Contact Number!", "Error", JOptionPane.ERROR_MESSAGE); return;
        }
        if (!dto.getEmail().matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
            JOptionPane.showMessageDialog(view, "Invalid Email!", "Error", JOptionPane.ERROR_MESSAGE); return;
        }
        
        // Validate Salary Number
        double salaryVal = 0.0;
        try {
            salaryVal = Double.parseDouble(dto.getSalary());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(view, "Invalid Salary Amount!", "Error", JOptionPane.ERROR_MESSAGE); return;
        }

        TeacherEntity entity = new TeacherEntity(
            dto.getTeacherId(), dto.getName(), dto.getNic(), dto.getBirthday(), dto.getContactNumber(), 
            dto.getEmail(), dto.getAddress(), dto.getGender(), salaryVal, dto.getPassword(), dto.getStatus()
        );
        
        if (dao.addTeacher(entity)) {
            JOptionPane.showMessageDialog(view, "Teacher Added Successfully!");
            new Thread(() -> AddTeacherEmailService.sendWelcomeEmail(dto)).start();
            view.clearFields();
            view.loadAutoGeneratedId(); 
            loadTableData();
        } else {
            JOptionPane.showMessageDialog(view, "Failed to Add! Email or NIC might already exist.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void loadTableData() {
        List<TeacherEntity> teachers = dao.getAllTeachers();
        DefaultTableModel model = (DefaultTableModel) view.getTable().getModel();
        model.setRowCount(0); 
        
        model.setColumnIdentifiers(new Object[]{"Teacher ID", "Name", "NIC", "Contact", "Email", "Salary", "Status"});
        for (TeacherEntity t : teachers) {
            model.addRow(new Object[]{
                t.getTeacherId(), t.getName(), t.getNic(), t.getContactNumber(), t.getEmail(), t.getSalary(), t.getStatus()
            });
        }
    }

    public void searchTeacher() {
        String searchId = view.getSearchId(); 
        if (searchId == null || searchId.trim().isEmpty()) {
            JOptionPane.showMessageDialog(view, "Please enter a Teacher ID!", "Warning", JOptionPane.WARNING_MESSAGE); return;
        }
        
        TeacherEntity teacher = dao.searchTeacher(searchId.trim()); 
        if (teacher != null) {
            TeacherDto dto = new TeacherDto(
                teacher.getTeacherId(), teacher.getName(), teacher.getNic(), teacher.getBirthday(), teacher.getContactNumber(),
                teacher.getEmail(), teacher.getAddress(), teacher.getGender(), String.valueOf(teacher.getSalary()), teacher.getPassword(), teacher.getStatus()
            );
            view.setTeacherData(dto); 
            JOptionPane.showMessageDialog(view, "Teacher Record Found!");
        } else {
            JOptionPane.showMessageDialog(view, "Teacher Not Found!", "Error", JOptionPane.ERROR_MESSAGE);
            view.clearFields();
            view.loadAutoGeneratedId(); 
        }
    }

    public void updateTeacher() {
        TeacherDto dto = view.getTeacherData();
        
        double salaryVal = 0.0;
        try { salaryVal = Double.parseDouble(dto.getSalary()); } 
        catch (NumberFormatException e) { JOptionPane.showMessageDialog(view, "Invalid Salary Amount!"); return; }

        TeacherEntity entity = new TeacherEntity(
            dto.getTeacherId(), dto.getName(), dto.getNic(), dto.getBirthday(), dto.getContactNumber(), 
            dto.getEmail(), dto.getAddress(), dto.getGender(), salaryVal, dto.getPassword(), dto.getStatus()
        );
        
        if (dao.updateTeacher(entity)) {
            JOptionPane.showMessageDialog(view, "Teacher Updated Successfully!");
            new Thread(() -> AddTeacherEmailService.sendUpdateEmail(dto)).start();
            view.clearFields();
            view.loadAutoGeneratedId();
            loadTableData();
        } else {
            JOptionPane.showMessageDialog(view, "Update Failed!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void deleteTeacher() {
        String teacherId = view.getTeacherData().getTeacherId();
        TeacherEntity teacher = dao.searchTeacher(teacherId);
        
        if (teacher == null) {
            JOptionPane.showMessageDialog(view, "Teacher Not Found to Delete!", "Error", JOptionPane.ERROR_MESSAGE); return;
        }

        int confirm = JOptionPane.showConfirmDialog(view, "Are you sure you want to delete this teacher?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (dao.deleteTeacher(teacherId)) {
                JOptionPane.showMessageDialog(view, "Teacher Deleted Successfully!");
                new Thread(() -> AddTeacherEmailService.sendDeleteEmail(teacher.getEmail(), teacher.getName(), teacherId)).start();
                view.clearFields();
                view.loadAutoGeneratedId();
                loadTableData();
            } else {
                JOptionPane.showMessageDialog(view, "Delete Failed!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    // ==============================================
    // EXCEL (CSV) Report Generate කිරීම
    // ==============================================
    public void exportToExcel() {
        // 1. Excel (CSV) එකේ මාතෘකා ටික (Headers)
        String headers = "Teacher ID,Full Name,NIC,Birthday,Contact Number,Email,Address,Gender,Salary,Status,Reg. Date";
        
        // 2. දත්ත පේළි (Rows) එකතු කිරීමට List එකක් සෑදීම
        java.util.List<String> dataRows = new java.util.ArrayList<>();
        java.util.List<TeacherEntity> teachers = dao.getAllTeachers();
        
        for (TeacherEntity t : teachers) {
            // Address එකේ කොමා (,) තිබුණොත් CSV එක කැඩෙන නිසා ඒවා Space එකකට මාරු කරනවා
            String safeAddress = t.getAddress() != null ? t.getAddress().replace(",", " ") : "";
            
            String row = t.getTeacherId() + "," +
                         t.getName() + "," +
                         t.getNic() + "," +
                         t.getBirthday() + "," +
                         t.getContactNumber() + "," +
                         t.getEmail() + "," +
                         safeAddress + "," +
                         t.getGender() + "," +
                         t.getSalary() + "," +
                         t.getStatus() + "," +
                         t.getRegistrationDate();
                         
            dataRows.add(row);
        }
        
        // 3. ඔයාගේ Export Connection එකට දත්ත යැවීම
        String defaultFileName = "Teachers_Official_Report.csv";
        ExcelExportConnection.ExcelExportService.exportToCSV(view, defaultFileName, headers, dataRows);
    }
    
    // ==============================================
    // PDF Report Generate කිරීම (HTML Template ආශ්‍රයෙන්)
    // ==============================================
    public void exportToPDF() {
        StringBuilder htmlBuilder = new StringBuilder();
        htmlBuilder.append("<!DOCTYPE html>");
        htmlBuilder.append("<html><head><style>")
                   .append("body { font-family: Helvetica, Arial, sans-serif; color: #333333; } ")
                   .append("table { width: 100%; border-collapse: collapse; font-size: 11px; margin-top: 10px; } ")
                   .append("th { background-color: #006B3C; color: #ffffff; padding: 10px; border: 1px solid #005530; text-align: left; } ")
                   .append("td { padding: 8px; border: 1px solid #dddddd; } ")
                   .append(".even-row { background-color: #F5F9F6; } ")
                   .append(".odd-row { background-color: #ffffff; } ")
                   .append(".status-active { color: #008000; font-weight: bold; } ")
                   .append(".status-inactive { color: #d9534f; font-weight: bold; } ")
                   .append("</style></head><body>");
        
        htmlBuilder.append("<div style='text-align: center; margin-bottom: 25px;'>");
        htmlBuilder.append("<img src='https://anucentralcollege.com/og-image.jpg' width='85' height='85' />");
        htmlBuilder.append("<h1 style='color: #006B3C; margin: 10px 0 2px 0; font-size: 24px; letter-spacing: 1px;'>")
                   .append("CENTRAL COLLEGE ANURADHAPURA</h1>");
        htmlBuilder.append("<h3 style='color: #666666; margin: 0; font-size: 14px; text-transform: uppercase;'>")
                   .append("Official Teacher Registration Report</h3>");
        htmlBuilder.append("<hr style='border: 0; border-bottom: 2px solid #D4AF37; margin-top: 15px;' />");
        htmlBuilder.append("</div>");
        
        htmlBuilder.append("<table>");
        htmlBuilder.append("<tr>")
                   .append("<th>Teacher ID</th>")
                   .append("<th>Full Name</th>")
                   .append("<th>NIC</th>")
                   .append("<th>Birthday</th>")
                   .append("<th>Contact</th>")
                   .append("<th>Email</th>")
                   .append("<th>Address</th>")
                   .append("<th>Gender</th>")
                   .append("<th>Salary (Rs)</th>")
                   .append("<th>Status</th>")
                   .append("<th>Reg. Date</th>")
                   .append("</tr>");

        java.util.List<Model.entity.TeacherEntity> teachers = dao.getAllTeachers();
        boolean isEvenRow = false;
        
        for(Model.entity.TeacherEntity t : teachers) {
            String rowClass = isEvenRow ? "even-row" : "odd-row";
            htmlBuilder.append("<tr class='").append(rowClass).append("'>");
            
            htmlBuilder.append("<td style='color: #B02A37; font-weight: bold;'>").append(t.getTeacherId()).append("</td>");
            htmlBuilder.append("<td>").append(t.getName()).append("</td>");
            htmlBuilder.append("<td>").append(t.getNic()).append("</td>");
            htmlBuilder.append("<td>").append(t.getBirthday()).append("</td>");
            htmlBuilder.append("<td>").append(t.getContactNumber()).append("</td>");
            htmlBuilder.append("<td>").append(t.getEmail()).append("</td>");
            htmlBuilder.append("<td>").append(t.getAddress()).append("</td>");
            htmlBuilder.append("<td>").append(t.getGender()).append("</td>");
            htmlBuilder.append("<td>").append(t.getSalary()).append("</td>"); // Salary එක එකතු කර ඇත
            
            String statusClass = t.getStatus().equalsIgnoreCase("Active") ? "status-active" : "status-inactive";
            htmlBuilder.append("<td class='").append(statusClass).append("'>").append(t.getStatus()).append("</td>");
            
            htmlBuilder.append("<td>").append(t.getRegistrationDate()).append("</td>");
            htmlBuilder.append("</tr>");
            
            isEvenRow = !isEvenRow; 
        }
        
        htmlBuilder.append("</table>");
        
        htmlBuilder.append("<div style='margin-top: 25px; padding: 12px 15px; background-color: #F8F9FA; border-left: 4px solid #006B3C;'>");
        htmlBuilder.append("<p style='font-size: 11px; color: #444444; margin: 0; line-height: 1.6;'>");
        htmlBuilder.append("<strong style='color: #006B3C;'>OFFICIAL SYSTEM NOTIFICATION:</strong><br/>");
        htmlBuilder.append("This is a computer-generated official report produced by the Central College Anuradhapura Staff Management System. ");
        htmlBuilder.append("As an electronically generated document, it does not require a physical signature or stamp for validation. ");
        htmlBuilder.append("Any discrepancies should be reported to the system administration immediately.");
        htmlBuilder.append("</p>");
        htmlBuilder.append("</div>");
        
        String currentdate = DateandTimeConnection.DateandTimeConnection.getInstance().getCurrentDate();
        
        htmlBuilder.append("<div style='margin-top: 30px; border-top: 1px solid #eeeeee; padding-top: 10px; text-align: center;'>");
        htmlBuilder.append("<p style='font-size: 10px; color: #888888; margin: 0;'>");
        htmlBuilder.append("Generated by Central College Anuradhapura Staff Management System | ").append(currentdate);
        htmlBuilder.append("</p>");
        htmlBuilder.append("</div>");
        
        htmlBuilder.append("</body></html>");
        
        try {
            // PDF Export Connection එක හරහා HTML එක PDF එකක් බවට පත් කිරීම
            PdfExportConnection.PdfExportConnection.getInstance().exportHTMLtoPDF(
                view, 
                "Teachers_Official_Report.pdf", 
                htmlBuilder.toString()
            );
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(view, "Error Generating PDF: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
}