package Controller;

import Model.dao.AdminStudentDAO;
import Model.dto.StudentDto;
import Model.entity.StudentEntity;
import View.AdminAddStuPanel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.text.ParseException;

public class AdminStudentController {
    
    private AdminAddStuPanel view;
    private AdminStudentDAO dao;

    public AdminStudentController(AdminAddStuPanel view) {
        this.view = view;
        try {
            this.dao = new AdminStudentDAO();
            loadTableData(); 
        } catch (Exception e) {
            System.out.println("Controller Load Error: " + e.getMessage());
        }
    }

    public void addStudent() {
        StudentDto dto = view.getStudentData();
        
        if (dto.getClassId() == null || dto.getClassId().trim().isEmpty()) {
            JOptionPane.showMessageDialog(view, "Please select a valid Class from the list!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        if (dto.getName().trim().isEmpty() || 
            dto.getBirthday().trim().isEmpty() || 
            dto.getContactNumber().trim().isEmpty() || 
            dto.getEmail().trim().isEmpty() || 
            dto.getAddress().trim().isEmpty() || 
            dto.getPassword().trim().isEmpty()) {
            
            JOptionPane.showMessageDialog(view, "Please fill in all the required fields!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return; 
        }

        if (!dto.getName().matches("^[a-zA-Z\\s]+$")) {
            JOptionPane.showMessageDialog(view, "Invalid Name! The name can only contain letters and spaces.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!isValidDate(dto.getBirthday())) {
            JOptionPane.showMessageDialog(view, "Invalid Birthday! Please enter a valid date in YYYY-MM-DD format (e.g. 2005-01-25).", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!dto.getContactNumber().matches("^\\d{10}$")) {
            JOptionPane.showMessageDialog(view, "Invalid Contact Number! Please enter a valid 10-digit phone number.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!dto.getEmail().matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
            JOptionPane.showMessageDialog(view, "Invalid Email Address! Please enter a valid email (e.g. example@gmail.com).", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        StudentEntity entity = new StudentEntity(
            dto.getStudentId(), dto.getName(), dto.getBirthday(), dto.getContactNumber(), 
            dto.getEmail(), dto.getAddress(), dto.getGender(), dto.getPassword(), dto.getStatus()
        );
        
        entity.setClassId(dto.getClassId());
        
        if (dao.addStudent(entity)) {
            JOptionPane.showMessageDialog(view, "Student Added Successfully!");
            
            new Thread(() -> {
                AddStuEmailService.sendWelcomeEmail(dto);
            }).start();
            
            view.clearFields();
            view.loadAutoGeneratedId(); 
            loadTableData();
        } else {
            JOptionPane.showMessageDialog(view, "Failed to Add Student! Email might already exist or Database error.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean isValidDate(String date) {
        if (!date.matches("^\\d{4}-\\d{2}-\\d{2}$")) {
            return false;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false);
        try {
            sdf.parse(date);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }

    public void loadTableData() {
        List<StudentEntity> students = dao.getAllStudents();
        DefaultTableModel model = (DefaultTableModel) view.getTable().getModel();
        model.setRowCount(0); 
        
        model.setColumnIdentifiers(new Object[]{"Student ID", "Name", "Contact", "Email", "Gender", "Class", "Status"});
        
        for (StudentEntity s : students) {
            model.addRow(new Object[]{
                s.getStudentId(), s.getName(), s.getContactNumber(), s.getEmail(), s.getGender(), s.getClassName(), s.getStatus()
            });
        }
    }

    public void searchStudent() {
        String searchId = view.getSearchId(); 
        
        if (searchId == null || searchId.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(view, "Please enter a Student ID to search!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        StudentEntity student = dao.searchStudent(searchId.trim()); 
        
        if (student != null) {
            StudentDto dto = new StudentDto(
                student.getStudentId(), student.getName(), student.getBirthday(), student.getContactNumber(),
                student.getEmail(), student.getAddress(), student.getGender(), student.getClassId(), student.getPassword(), student.getStatus()
            );
            
            view.setStudentData(dto); 
            javax.swing.JOptionPane.showMessageDialog(view, "Student Record Found!");
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(view, "Student Not Found!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            view.clearFields();
            view.loadAutoGeneratedId(); 
        }
    }

    public void updateStudent() {
        StudentDto dto = view.getStudentData();
        
        StudentEntity entity = new StudentEntity(
            dto.getStudentId(), dto.getName(), dto.getBirthday(), dto.getContactNumber(), 
            dto.getEmail(), dto.getAddress(), dto.getGender(), dto.getPassword(), dto.getStatus()
        );
        entity.setClassId(dto.getClassId());
        
        if (dao.updateStudent(entity)) {
            JOptionPane.showMessageDialog(view, "Student Updated Successfully!");
            new Thread(() -> AddStuEmailService.sendUpdateEmail(dto)).start();
            view.clearFields();
            view.loadAutoGeneratedId();
            loadTableData();
        } else {
            JOptionPane.showMessageDialog(view, "Update Failed!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void deleteStudent() {
        String studentId = view.getStudentData().getStudentId();
        StudentEntity student = dao.searchStudent(studentId);
        
        if (student == null) {
            JOptionPane.showMessageDialog(view, "Student not found! Please search and confirm the student before attempting to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(view, "Are you sure you want to delete this student?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (dao.deleteStudent(studentId)) {
                JOptionPane.showMessageDialog(view, "Student Deleted Successfully!");
                
                String email = student.getEmail();
                String name = student.getName();
                new Thread(() -> AddStuEmailService.sendDeleteEmail(email, name, studentId)).start();
                
                view.clearFields();
                view.loadAutoGeneratedId();
                loadTableData();
            } else {
                JOptionPane.showMessageDialog(view, "Delete Failed!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    // --- Export Data to Excel ---
    public void exportToExcel() {
        String headers = "Student ID,Full Name,Birthday,Contact Number,Email,Address,Gender,Class,Account Status,Registration Date";     
        java.util.List<String> dataRows = new java.util.ArrayList<>();
        java.util.List<Model.entity.StudentEntity> students = dao.getAllStudents();
        
        for(Model.entity.StudentEntity s : students) {
            String cleanAddress = s.getAddress().replace(",", " ");
            
            // වෙනස: getClassId වෙනුවට getClassName භාවිතා කර ඇත
            String className = s.getClassName() != null ? s.getClassName() : "-"; 
            
            String row = s.getStudentId() + "," + 
                         s.getName() + "," + 
                         s.getBirthday() + "," + 
                         s.getContactNumber() + "," + 
                         s.getEmail() + "," + 
                         cleanAddress + "," + 
                         s.getGender() + "," + 
                         className + "," + 
                         s.getStatus() + "," + 
                         s.getRegistrationDate();
                         
            dataRows.add(row);
        }
        ExcelExportConnection.ExcelExportService.exportToCSV(view, "Students_Report.csv", headers, dataRows);
    }
    
    // --- Export Data to PDF ---
    public void exportToPDF() {
        StringBuilder htmlBuilder = new StringBuilder();
        htmlBuilder.append("<!DOCTYPE html>");
        htmlBuilder.append("<html><head><style>")
                   .append("body { font-family: Helvetica, Arial, sans-serif; color: #333333; } ")
                   .append("table { width: 100%; border-collapse: collapse; font-size: 11px; margin-top: 10px; } ")
                   .append("th { background-color: #006B3C; color: #ffffff; padding: 10px; border: 1px solid #005530; text-align: left; } ")
                   .append("td { padding: 8px; border: 1px solid #dddddd; } ")
                   .append(".even-row { background-color: #F5F9F6; } ")
                   .append(".odd-row { background-color: #ffffff; } ")
                   .append(".status-active { color: #008000; font-weight: bold; } ")
                   .append(".status-inactive { color: #d9534f; font-weight: bold; } ")
                   .append("</style></head><body>");
        
        htmlBuilder.append("<div style='text-align: center; margin-bottom: 25px;'>");
        htmlBuilder.append("<img src='https://anucentralcollege.com/og-image.jpg' width='85' height='85' />");
        htmlBuilder.append("<h1 style='color: #006B3C; margin: 10px 0 2px 0; font-size: 24px; letter-spacing: 1px;'>")
                   .append("CENTRAL COLLEGE ANURADHAPURA</h1>");
        htmlBuilder.append("<h3 style='color: #666666; margin: 0; font-size: 14px; text-transform: uppercase;'>")
                   .append("Official Student Registration Report</h3>");
        htmlBuilder.append("<hr style='border: 0; border-bottom: 2px solid #D4AF37; margin-top: 15px;' />");
        htmlBuilder.append("</div>");
        
        htmlBuilder.append("<table>");
        htmlBuilder.append("<tr>")
                   .append("<th>Student ID</th>")
                   .append("<th>Full Name</th>")
                   .append("<th>Birthday</th>")
                   .append("<th>Contact</th>")
                   .append("<th>Email</th>")
                   .append("<th>Address</th>")
                   .append("<th>Gender</th>")
                   .append("<th>Class</th>")
                   .append("<th>Status</th>")
                   .append("<th>Reg. Date</th>")
                   .append("</tr>");

        java.util.List<Model.entity.StudentEntity> students = dao.getAllStudents();
        boolean isEvenRow = false;
        
        for(Model.entity.StudentEntity s : students) {
            String rowClass = isEvenRow ? "even-row" : "odd-row";
            htmlBuilder.append("<tr class='").append(rowClass).append("'>");
            
            htmlBuilder.append("<td style='color: #B02A37; font-weight: bold;'>").append(s.getStudentId()).append("</td>");
            htmlBuilder.append("<td>").append(s.getName()).append("</td>");
            htmlBuilder.append("<td>").append(s.getBirthday()).append("</td>");
            htmlBuilder.append("<td>").append(s.getContactNumber()).append("</td>");
            htmlBuilder.append("<td>").append(s.getEmail()).append("</td>");
            htmlBuilder.append("<td>").append(s.getAddress()).append("</td>");
            htmlBuilder.append("<td>").append(s.getGender()).append("</td>");
            
            // වෙනස: getClassId වෙනුවට getClassName භාවිතා කර ඇත
            String className = s.getClassName() != null ? s.getClassName() : "-";
            htmlBuilder.append("<td>").append(className).append("</td>");
            
            String statusClass = s.getStatus().equalsIgnoreCase("Active") ? "status-active" : "status-inactive";
            htmlBuilder.append("<td class='").append(statusClass).append("'>").append(s.getStatus()).append("</td>");
            
            htmlBuilder.append("<td>").append(s.getRegistrationDate()).append("</td>");
            htmlBuilder.append("</tr>");
            
            isEvenRow = !isEvenRow; 
        }
        
        htmlBuilder.append("</table>");
        
        htmlBuilder.append("<div style='margin-top: 25px; padding: 12px 15px; background-color: #F8F9FA; border-left: 4px solid #006B3C;'>");
        htmlBuilder.append("<p style='font-size: 11px; color: #444444; margin: 0; line-height: 1.6;'>");
        htmlBuilder.append("<strong style='color: #006B3C;'>OFFICIAL SYSTEM NOTIFICATION:</strong><br/>");
        htmlBuilder.append("This is a computer-generated official report produced by the Central College Anuradhapura Student Management System. ");
        htmlBuilder.append("As an electronically generated document, it does not require a physical signature or stamp for validation. ");
        htmlBuilder.append("Any discrepancies should be reported to the system administration immediately.");
        htmlBuilder.append("</p>");
        htmlBuilder.append("</div>");
        
        String currentdate = DateandTimeConnection.DateandTimeConnection.getInstance().getCurrentDate();
        
        htmlBuilder.append("<div style='margin-top: 30px; border-top: 1px solid #eeeeee; padding-top: 10px; text-align: center;'>");
        htmlBuilder.append("<p style='font-size: 10px; color: #888888; margin: 0;'>");
        htmlBuilder.append("Generated by Central College Anuradhapura Student Management System | " + currentdate);
        htmlBuilder.append("</p>");
        htmlBuilder.append("</div>");
        
        htmlBuilder.append("</body></html>");
        
        PdfExportConnection.PdfExportConnection.getInstance().exportHTMLtoPDF(
            view, 
            "Students_Official_Report.pdf", 
            htmlBuilder.toString()
        );
    }
}