/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;


/**
 *
 * @author User
 */
public class AdminAddStuPanel extends javax.swing.JPanel {
    private Controller.AdminStudentController controller;
   
    /**
     * Creates new form Stusubject
     */
    public AdminAddStuPanel() {
       initComponents();
        
       controller = new Controller.AdminStudentController(this);
        loadAutoGeneratedId();
        setCurrentdate();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jstuTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTxtCnumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtbirthday = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtpsw = new javax.swing.JTextField();
        jTxtaddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jBtnadd = new javax.swing.JButton();
        jbtndelete = new javax.swing.JButton();
        jbtnupdate = new javax.swing.JButton();
        jbtnEXreport = new javax.swing.JButton();
        jComboBoxstatus = new javax.swing.JComboBox<>();
        jbtnseartch = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxgender = new javax.swing.JComboBox<>();
        stuid = new javax.swing.JLabel();
        jlbregistrationdate = new javax.swing.JLabel();
        txtsertchid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtclear = new javax.swing.JButton();
        jbtnPDFreport = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        jstuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jstuTable);

        jLabel1.setText("Student ID: ");

        jTxtCnumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setText("Name: ");

        jTxtname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setText("Contact Number");

        jTxtbirthday.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setText("Email:");

        jTxtemail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setText("Birthday: ");

        jLabel7.setText("Registration Date: ");

        jLabel8.setText("Password:");

        jTxtpsw.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTxtaddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setText("Address: ");

        jBtnadd.setBackground(new java.awt.Color(51, 255, 51));
        jBtnadd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnadd.setForeground(new java.awt.Color(255, 255, 255));
        jBtnadd.setText("Add");
        jBtnadd.addActionListener(this::jBtnaddActionPerformed);

        jbtndelete.setBackground(new java.awt.Color(255, 0, 0));
        jbtndelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtndelete.setForeground(new java.awt.Color(255, 255, 255));
        jbtndelete.setText("Delete");
        jbtndelete.addActionListener(this::jbtndeleteActionPerformed);

        jbtnupdate.setBackground(new java.awt.Color(0, 0, 153));
        jbtnupdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnupdate.setForeground(new java.awt.Color(255, 255, 255));
        jbtnupdate.setText("Update");
        jbtnupdate.addActionListener(this::jbtnupdateActionPerformed);

        jbtnEXreport.setBackground(new java.awt.Color(0, 153, 0));
        jbtnEXreport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnEXreport.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEXreport.setText("Get Excel Reoprt");
        jbtnEXreport.setToolTipText("");
        jbtnEXreport.addActionListener(this::jbtnEXreportActionPerformed);

        jComboBoxstatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBoxstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Deactivated" }));
        jComboBoxstatus.addActionListener(this::jComboBoxstatusActionPerformed);

        jbtnseartch.setBackground(new java.awt.Color(255, 153, 0));
        jbtnseartch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnseartch.setForeground(new java.awt.Color(255, 255, 255));
        jbtnseartch.setText("Seartch by Id");
        jbtnseartch.setToolTipText("");
        jbtnseartch.addActionListener(this::jbtnseartchActionPerformed);

        jLabel10.setText("Gender: ");

        jLabel11.setText("Status");

        jComboBoxgender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBoxgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jComboBoxgender.addActionListener(this::jComboBoxgenderActionPerformed);

        stuid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stuid.setText("student_id");

        jlbregistrationdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbregistrationdate.setText("Registation Date");

        txtsertchid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel12.setText("Enter Studnt ID: ");

        txtclear.setBackground(new java.awt.Color(0, 0, 0));
        txtclear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtclear.setForeground(new java.awt.Color(255, 255, 255));
        txtclear.setText("Clear");
        txtclear.addActionListener(this::txtclearActionPerformed);

        jbtnPDFreport.setBackground(new java.awt.Color(255, 51, 51));
        jbtnPDFreport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnPDFreport.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPDFreport.setText("Get PDF Reoprt");
        jbtnPDFreport.setToolTipText("");
        jbtnPDFreport.addActionListener(this::jbtnPDFreportActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jlbregistrationdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(stuid)
                            .addComponent(jLabel10)
                            .addComponent(jComboBoxgender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtnseartch, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtsertchid, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jTxtname, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTxtbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel8))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTxtpsw, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(txtclear))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jTxtCnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtnEXreport, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnPDFreport, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTxtname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxtbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxtCnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(stuid)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(48, 48, 48)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtemail)
                    .addComponent(jComboBoxgender)
                    .addComponent(jTxtaddress)
                    .addComponent(txtclear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtpsw))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbregistrationdate)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBtnadd)
                                    .addComponent(jbtndelete))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnupdate)
                            .addComponent(jbtnseartch)
                            .addComponent(txtsertchid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEXreport, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPDFreport, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnaddActionPerformed
        controller.addStudent();
    }//GEN-LAST:event_jBtnaddActionPerformed

    private void jbtndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndeleteActionPerformed
        controller.deleteStudent();
        }//GEN-LAST:event_jbtndeleteActionPerformed

    private void jbtnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnupdateActionPerformed
        controller.updateStudent();
    }//GEN-LAST:event_jbtnupdateActionPerformed

    private void jbtnEXreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEXreportActionPerformed
       controller.exportToExcel();
       
    }//GEN-LAST:event_jbtnEXreportActionPerformed

    private void jComboBoxstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxstatusActionPerformed

    private void jbtnseartchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnseartchActionPerformed
        controller.searchStudent();
    }//GEN-LAST:event_jbtnseartchActionPerformed

    private void jComboBoxgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxgenderActionPerformed

    private void txtclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclearActionPerformed
         clearFields();
         loadAutoGeneratedId();
         setCurrentdate();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclearActionPerformed

    private void jbtnPDFreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPDFreportActionPerformed
        controller.exportToPDF();        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPDFreportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnadd;
    private javax.swing.JComboBox<String> jComboBoxgender;
    private javax.swing.JComboBox<String> jComboBoxstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtCnumber;
    private javax.swing.JTextField jTxtaddress;
    private javax.swing.JTextField jTxtbirthday;
    private javax.swing.JTextField jTxtemail;
    private javax.swing.JTextField jTxtname;
    private javax.swing.JTextField jTxtpsw;
    private javax.swing.JButton jbtnEXreport;
    private javax.swing.JButton jbtnPDFreport;
    private javax.swing.JButton jbtndelete;
    private javax.swing.JButton jbtnseartch;
    private javax.swing.JButton jbtnupdate;
    private javax.swing.JLabel jlbregistrationdate;
    private javax.swing.JTable jstuTable;
    private javax.swing.JLabel stuid;
    private javax.swing.JButton txtclear;
    private javax.swing.JTextField txtsertchid;
    // End of variables declaration//GEN-END:variables

// Controller එකට JTable එක ලබාදීම සඳහා මෙය AdminAddStuPanel එක තුළ තිබිය යුතුය
    public javax.swing.JTable getTable() {
        return jstuTable; //student table
    }
    
    public void loadAutoGeneratedId() {
        try {
            Model.dao.AdminStudentDAO dao = new Model.dao.AdminStudentDAO();
            stuid.setText(dao.generateNextStudentId());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void clearFields() {
        jTxtname.setText("");
        jTxtbirthday.setText("");
        jTxtCnumber.setText("");
        jTxtemail.setText("");
        jTxtaddress.setText("");
        jTxtpsw.setText("");
        txtsertchid.setText("");
    }
    
    // 4. Controller එකට දත්ත ලබා දෙන getStudentData Method එක නැවත එක් කරන ලදි
    public Model.dto.StudentDto getStudentData() {
        return new Model.dto.StudentDto(
            stuid.getText(),
            jTxtname.getText(),
            jTxtbirthday.getText(),
            jTxtCnumber.getText(),
            jTxtemail.getText(),
            jTxtaddress.getText(),
            jComboBoxgender.getSelectedItem().toString(),
            jTxtpsw.getText(),
            jComboBoxstatus.getSelectedItem().toString()
        );
    }
    // Search කළ දත්ත UI එකේ පෙන්වීම සඳහා
    public void setStudentData(Model.dto.StudentDto dto) {
        stuid.setText(dto.getStudentId());
        jTxtname.setText(dto.getName());
        jTxtbirthday.setText(dto.getBirthday());
        jTxtCnumber.setText(dto.getContactNumber());
        jTxtemail.setText(dto.getEmail());
        jTxtaddress.setText(dto.getAddress());
        jComboBoxgender.setSelectedItem(dto.getGender());
        jTxtpsw.setText(dto.getPassword());
        jComboBoxstatus.setSelectedItem(dto.getStatus());
    }
    
    // Search Text Field එකෙන් ID එක ලබා ගැනීම
    public String getSearchId() {
        return txtsertchid.getText(); 
    }
    public void setCurrentdate(){
        try {
            jlbregistrationdate.setText(DateandTimeConnection.DateandTimeConnection.getInstance().getCurrentDate());
        } catch (Exception e) {
            jlbregistrationdate.setText("Error loading date");
        }
        
    }
}