/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LoginController;
import Model.dao.LoginDAO;
import java.awt.event.ActionListener;
/**
 *
 * @author User
 */
public class Loginview extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Loginview.class.getName());

    /**
     * Creates new form Loginview
     */
    private LoginController controller;
    public Loginview() {
       initComponents();
        setLocationRelativeTo(null);
        try {
            LoginDAO dao = new LoginDAO();
            // 1. Controller එක ඔබject එකක් විදියට හදනවා
            controller = new LoginController(this, dao);
            
        } catch (Exception e) {
            System.out.println("Login Controller Initialization Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        adminemail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        adminpsw = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/school logo.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jLabel3.setText("Welcome back");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        btnlogin.setBackground(new java.awt.Color(0, 204, 51));
        btnlogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("Loging");
        btnlogin.addActionListener(this::btnloginActionPerformed);
        jPanel1.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 100, -1));

        btnback.setBackground(new java.awt.Color(51, 0, 153));
        btnback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.addActionListener(this::btnbackActionPerformed);
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 100, -1));

        adminemail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adminemail.setForeground(new java.awt.Color(0, 0, 51));
        adminemail.addActionListener(this::adminemailActionPerformed);
        jPanel1.add(adminemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 270, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 166, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Email");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 166, -1));

        jLabel4.setText("Log in to CCA School Management System");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Forgot Password ?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Students ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("200+");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Teachers");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("200+");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        adminpsw.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adminpsw.setForeground(new java.awt.Color(0, 0, 51));
        adminpsw.addActionListener(this::adminpswActionPerformed);
        jPanel1.add(adminpsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 270, -1));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.green, java.awt.Color.yellow, java.awt.Color.orange));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 300, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 380, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminemailActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed

    }//GEN-LAST:event_btnloginActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
                int choice = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to back?", 
                "back Confirmation", 
                javax.swing.JOptionPane.YES_NO_OPTION);

        
        if (choice == javax.swing.JOptionPane.YES_OPTION) {
            
            //  Dashboard
            this.dispose(); 
            // Startview ( Login)
            View.Startview startPage = new View.Startview();
            startPage.setVisible(true);
        }  
    }//GEN-LAST:event_btnbackActionPerformed

    private void adminpswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminpswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminpswActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        // if have database error we mange using try and catch
            java.awt.EventQueue.invokeLater(() -> {
            try {
                // මේක try block එකක් ඇතුළට දැම්මම අර SQL Error එක එන්නේ නැහැ
                Loginview view = new Loginview();
                Model.dao.LoginDAO dao = new Model.dao.LoginDAO();
                new Controller.LoginController(view, dao);
                view.setVisible(true);
                
            } catch (Exception ex) {
                // මොකක් හරි දෝෂයක් ආවොත් ඒක මෙතැනින් අල්ලගන්නවා
                System.out.println("System Load Error: " + ex.getMessage());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminemail;
    private javax.swing.JTextField adminpsw;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

public String getEmail() { 
    return adminemail.getText().trim();
}
    public String getPassword() { 
        return adminpsw.getText().trim();
    }
    public void clearPassword() {
        adminpsw.setText("");
    }

    // 2. Controller එකට Button එක Listen කරන්න දෙන Method එක

public void addLoginListener(ActionListener listener) {
        btnlogin.addActionListener(listener); 
    }
  
  }
