/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import DateandTimeConnection.DateandTimeConnection;
/**
 *
 * @author User
 */
public class Startview extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Startview.class.getName());

    /**
     * Creates new form startview
     */
    public Startview() {
        initComponents();
        setLocationRelativeTo(null);
        startDateTimeTimer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void startDateTimeTimer() {
        // 1000 milliseconds කියන්නේ හරියටම තත්පර 1ක්. 
        // ඒ කියන්නේ තත්පර 1 කට වතාවක් මේ ඇතුළේ තියෙන කෝඩ් එක රන් වෙනවා.
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Singleton එකෙන් වර්තමාන දිනය සහ වෙලාව ලබා ගැනීම
                String currentDate = DateandTimeConnection.getInstance().getCurrentDate();
                
                // ඔබගේ JLabel එකේ නම 'datetimelabel' නම් මෙන්න මෙහෙම Set කරන්න
                dateandtime.setText(currentDate);
            }
        });
        
        // Timer එක ක්‍රියාත්මක කිරීම
        timer.start();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateandtime = new javax.swing.JLabel();
        btnadmin = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        startimgbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateandtime.setBackground(new java.awt.Color(255, 255, 255));
        dateandtime.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        dateandtime.setForeground(new java.awt.Color(255, 255, 255));
        dateandtime.setText("Date ");
        getContentPane().add(dateandtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        btnadmin.setBackground(new java.awt.Color(0, 153, 0));
        btnadmin.setFont(new java.awt.Font("Rockwell Condensed", 1, 12)); // NOI18N
        btnadmin.setForeground(new java.awt.Color(255, 255, 255));
        btnadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/help-desk (1).png"))); // NOI18N
        btnadmin.setText("Help");
        btnadmin.addActionListener(this::btnadminActionPerformed);
        getContentPane().add(btnadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 550, 170, 30));

        btnlogout.setBackground(new java.awt.Color(255, 0, 51));
        btnlogout.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("Logout");
        btnlogout.addActionListener(this::btnlogoutActionPerformed);
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 140, 40));

        btnlogin.setBackground(new java.awt.Color(0, 0, 102));
        btnlogin.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("Login");
        btnlogin.addActionListener(this::btnloginActionPerformed);
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 140, 40));

        startimgbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/newstartbg.jpeg"))); // NOI18N
        getContentPane().add(startimgbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        View.Loginview loginview = new View.Loginview();
        loginview.setVisible(true);     
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
         this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminActionPerformed
// 1. View  Pop-up 
        String[] requestData = View.SupportPopupView.showSupportTicketDialog(this);
        
        // 2. User OK
        if (requestData != null) {
            String userInfo = requestData[0];
            String message = requestData[1];
            String attachment = requestData[2];
            
            Controller.CommonSupportController supportCtrl = new Controller.CommonSupportController(this);
            supportCtrl.processSupportRequest(userInfo, message, attachment);
        }     
    }//GEN-LAST:event_btnadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
// --- SPLASH SCREEN CODE START ---
        javax.swing.JWindow splashWindow = new javax.swing.JWindow();
        
        // හිස් සුදු පසුබිම වෙනුවට Gradient Background එකක් යෙදීම
        javax.swing.JPanel contentPanel = new javax.swing.JPanel(new java.awt.BorderLayout()) {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;
                g2d.setRenderingHint(java.awt.RenderingHints.KEY_RENDERING, java.awt.RenderingHints.VALUE_RENDER_QUALITY);
                
                // ඉහළින් සුදු පැහැය සහ පහළින් ඉතා ලා කොළ පැහැය (Soft Light Green)
                java.awt.Color color1 = java.awt.Color.WHITE;
                java.awt.Color color2 = new java.awt.Color(230, 245, 235); 
                java.awt.GradientPaint gp = new java.awt.GradientPaint(0, 0, color1, 0, getHeight(), color2);
                
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        
        // Professional Theme Border: පිටතින් Green (4px) සහ ඇතුළතින් Yellow (2px)
        contentPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 4), // Dark Green
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2) // Bright Yellow
        )); 

        // Logo Image
        java.net.URL imgURL = Startview.class.getResource("/image/school_logo_removebg.png");
        if (imgURL != null) {
            javax.swing.JLabel lblLogo = new javax.swing.JLabel(new javax.swing.ImageIcon(imgURL), javax.swing.SwingConstants.CENTER);
            contentPanel.add(lblLogo, java.awt.BorderLayout.CENTER);
        } else {
            javax.swing.JLabel lblFallback = new javax.swing.JLabel("CCA Logo", javax.swing.SwingConstants.CENTER);
            lblFallback.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 48)); 
            lblFallback.setForeground(new java.awt.Color(0, 102, 51)); // Dark Green
            contentPanel.add(lblFallback, java.awt.BorderLayout.CENTER);
        }
        
        // Bottom Panel for Text & Progress Bar (පසුබිම පෙනීමට Opaque(false) කර ඇත)
        javax.swing.JPanel bottomPanel = new javax.swing.JPanel(new java.awt.BorderLayout());
        bottomPanel.setOpaque(false); 
        
        // Text Container
        javax.swing.JPanel textPanel = new javax.swing.JPanel(new java.awt.GridLayout(2, 1));
        textPanel.setOpaque(false); 
        textPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 20, 0));
        
        javax.swing.JLabel lblTitle = new javax.swing.JLabel("CENTRAL COLLEGE ANURADHAPURA", javax.swing.SwingConstants.CENTER);
        lblTitle.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 28)); 
        lblTitle.setForeground(new java.awt.Color(0, 102, 51)); // Dark Green

        javax.swing.JLabel lblLoading = new javax.swing.JLabel("Management System - Starting up...", javax.swing.SwingConstants.CENTER);
        lblLoading.setFont(new java.awt.Font("Segoe UI", java.awt.Font.ITALIC, 16)); 
        lblLoading.setForeground(new java.awt.Color(80, 120, 80)); // අකුරු වඩාත් පැහැදිලි වීමට

        textPanel.add(lblTitle);
        textPanel.add(lblLoading);

        // --- MODERN CUSTOM ANIMATED PROGRESS BAR ---
        final float[] progress = {0f};
        javax.swing.JPanel progressBar = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2d = (java.awt.Graphics2D) g.create();
                g2d.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                
                // Track Background (ලා අළු-කොළ පැහැති තීරුව)
                g2d.setColor(new java.awt.Color(210, 225, 215));
                g2d.fillRect(0, 0, getWidth(), getHeight());
                
                // Filling Gradient (තද කොළ පැහැයේ සිට කහ පැහැයට පිරීගෙන යෑම)
                int currentWidth = (int) (getWidth() * (progress[0] / 100f));
                if (currentWidth > 0) {
                    java.awt.GradientPaint gp = new java.awt.GradientPaint(0, 0, new java.awt.Color(0, 102, 51), currentWidth, 0, new java.awt.Color(255, 204, 0));
                    g2d.setPaint(gp);
                    g2d.fillRect(0, 0, currentWidth, getHeight());
                }
                g2d.dispose();
            }
        };
        progressBar.setPreferredSize(new java.awt.Dimension(1030, 6)); // උස 6px කර සිහින්, නවීන පෙනුමක් ලබා දී ඇත
        progressBar.setOpaque(false);

        // තත්පර 5ක් (5000ms) ඇතුළත ඉතා සුමටව (60fps) progress line එක පිරවීමට Timer එකක්
        javax.swing.Timer timer = new javax.swing.Timer(16, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                progress[0] += (100f / (5000f / 16f)); 
                if (progress[0] >= 100f) {
                    progress[0] = 100f;
                    ((javax.swing.Timer)e.getSource()).stop();
                }
                progressBar.repaint();
            }
        });
        timer.start();
        // --------------------------------------------

        bottomPanel.add(textPanel, java.awt.BorderLayout.CENTER);
        bottomPanel.add(progressBar, java.awt.BorderLayout.SOUTH); // පතුළටම Progress bar එක සවි කිරීම

        contentPanel.add(bottomPanel, java.awt.BorderLayout.SOUTH);

        splashWindow.getContentPane().add(contentPanel);
        
        // Window size 1030x600
        splashWindow.setSize(1030, 600); 
        splashWindow.setLocationRelativeTo(null); 
        splashWindow.setVisible(true);

        try {
            Thread.sleep(5800); // තත්පර 5ක් පෙන්වීමට 
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        splashWindow.dispose();
        // --- SPLASH SCREEN CODE END ---
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Startview().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadmin;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel dateandtime;
    private javax.swing.JLabel startimgbg;
    // End of variables declaration//GEN-END:variables
}
