/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import DateandTimeConnection.DateandTimeConnection;
/**
 *
 * @author User
 */
public class Startview extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Startview.class.getName());

    /**
     * Creates new form startview
     */
    public Startview() {
        initComponents();
        setLocationRelativeTo(null);
        startDateTimeTimer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void startDateTimeTimer() {
        // 1000 milliseconds කියන්නේ හරියටම තත්පර 1ක්. 
        // ඒ කියන්නේ තත්පර 1 කට වතාවක් මේ ඇතුළේ තියෙන කෝඩ් එක රන් වෙනවා.
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Singleton එකෙන් වර්තමාන දිනය සහ වෙලාව ලබා ගැනීම
                String currentDate = DateandTimeConnection.getInstance().getCurrentDate();
                
                // ඔබගේ JLabel එකේ නම 'datetimelabel' නම් මෙන්න මෙහෙම Set කරන්න
                dateandtime.setText(currentDate);
            }
        });
        
        // Timer එක ක්‍රියාත්මක කිරීම
        timer.start();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateandtime = new javax.swing.JLabel();
        btnadmin = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        startimgbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateandtime.setBackground(new java.awt.Color(255, 255, 255));
        dateandtime.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        dateandtime.setForeground(new java.awt.Color(255, 255, 255));
        dateandtime.setText("Date ");
        getContentPane().add(dateandtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        btnadmin.setBackground(new java.awt.Color(0, 153, 0));
        btnadmin.setFont(new java.awt.Font("Rockwell Condensed", 1, 12)); // NOI18N
        btnadmin.setForeground(new java.awt.Color(255, 255, 255));
        btnadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/help-desk (1).png"))); // NOI18N
        btnadmin.setText("Help");
        btnadmin.addActionListener(this::btnadminActionPerformed);
        getContentPane().add(btnadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 550, 170, 30));

        btnlogout.setBackground(new java.awt.Color(255, 0, 51));
        btnlogout.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("Logout");
        btnlogout.addActionListener(this::btnlogoutActionPerformed);
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 140, 40));

        btnlogin.setBackground(new java.awt.Color(0, 0, 102));
        btnlogin.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("Login");
        btnlogin.addActionListener(this::btnloginActionPerformed);
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 140, 40));

        startimgbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/newstartbg.jpeg"))); // NOI18N
        getContentPane().add(startimgbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        View.Loginview loginview = new View.Loginview();
        loginview.setVisible(true);     
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminActionPerformed
// 1. View  Pop-up 
        String[] requestData = View.SupportPopupView.showSupportTicketDialog(this);
        
        // 2. User OK
        if (requestData != null) {
            String userInfo = requestData[0];
            String message = requestData[1];
            String attachment = requestData[2];
            
            Controller.CommonSupportController supportCtrl = new Controller.CommonSupportController(this);
            supportCtrl.processSupportRequest(userInfo, message, attachment);
        }     
    }//GEN-LAST:event_btnadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Startview().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadmin;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel dateandtime;
    private javax.swing.JLabel startimgbg;
    // End of variables declaration//GEN-END:variables
}
